version: "3.8"

networks:
  app-tier:
    driver: bridge

services:
  kafka:
    container_name: yagram-dev-kafka
    image: docker.io/bitnami/kafka:3.4
    networks:
      - app-tier
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes

  socket-service:
    depends_on:
      - kafka
    container_name: yagram-dev-socket-service
    build:
      context: .
      dockerfile: socket-service/dev.Dockerfile
    networks:
      - app-tier
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./socket-service
        target: /usr/local/app/socket-service

  message-handler-service:
    depends_on:
      - kafka
    container_name: yagram-dev-message-handler-service
    build:
      context: .
      dockerfile: message-handler-service/dev.Dockerfile
    networks:
      - app-tier
    volumes:
      - type: bind
        source: ./message-handler-service
        target: /usr/local/app/message-handler-service

volumes:
  kafka_data:
    driver: local

