import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, { useEffect, useState } from "react";
import MenuButton from "./components/header/MenuButton";
import GreetUser from "./components/header/GreetUser";
import IconUser from "./components/header/IconUser";
import Search from "./components/contacts/Search";
import Chat from "./components/chat/Chat";
import ContactList from "./components/contacts/Contact";
import profilePicMarvin from "./components/contacts/marvin-4.130912.130920.png";
import profilePicGendalf from "./components/contacts/gendalf.jpeg";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Yagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.container}>
          <div className={styles.header_wrapper}>
            <a href="/" className={styles.header_logo}>
              Yagram
            </a>
            <MenuButton />
            <GreetUser />
            <IconUser />
          </div>
          {/* header_wrapper */}
        </div>
        {/* container */}
      </header>
      <section className={styles.main_space}>
        <div className={styles.contacts}>
          <Search />
          <div>
            <ContactList
              contacts={[
                {
                  id: "1",
                  name: "Maksim",
                  lastMessage: "hello",
                  avatar: profilePicMarvin,
                  isOnline: true,
                },
                {
                  id: "2",
                  name: "Kostya",
                  lastMessage: "hello!",
                  avatar: profilePicGendalf,
                  isOnline: false,
                },
              ]}
            />
          </div>
        </div>
        <div className={styles.chat}>
          {/* Messages */}
          <Chat />
        </div>
      </section>
    </div>
  );
}
