import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, { useEffect, useState } from "react";
import MenuButton from "./components/header/MenuButton";
import GreetUser from "./components/header/GreetUser";
import IconUser from "./components/header/IconUser";
import Search from ".//components/contacts/Search";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Yagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.container}>
          <div className={styles.header_wrapper}>
            <a href="/" className={styles.header_logo}>
              Yagram
            </a>
            <MenuButton />
            <GreetUser />
            <IconUser />
          </div>
          {/* header_wrapper */}
        </div>
        {/* container */}
      </header>
      <section className={styles.main_space}>
        <div className={styles.contacts}>
          <Search />
        </div>
        <div className={styles.chat}></div>
      </section>
    </div>
  );
}
